### ISSUE TITLE
Accessors should be type checked

### ISSUE THREAD

**Issue by bkuehnert** [qitab/cl-protobufs#183]
Copy and pasted from internal bug b/159352737:

Setters, at least message and group setters, should check set type.
We set the type of on group/ message fields in proto to be
(or nil message-type) instead of message-type. This is so
we don't cons an unneeded proto structure.
This means we can setf the field to nil without, which shouldn't be allowed.
We can fix this by type-checking the input.

We should also declare the return type of an accessor.
This will allow a smarter compilation.

**Comment by Slids** [comment]
For setters we used declare, so it works for SBCL.
On other compilers it does lesser things...

For the accessors we use "the" so the return is properly typed.
