### ISSUE TITLE
abcl tests are using the quicklisp version of  cl-protobufs in testing

### ISSUE THREAD

**Issue by Slids** [qitab/cl-protobufs#199]
Not sure why this is happening, but we can see running:
https://github.com/Slids/cl-protobufs/runs/1044380174?check_suite_focus=true
it's true.

**Comment by easye** [comment]
@slids I fixed a regressin in ABCL that prevented Quicklisp from properly finding ASDF systems in the quicklisp/local-projects/ directory. 

<https://github.com/armedbear/abcl/commit/7789522b366b6a99eb19bc5652d61d8a0013c6a9>

You should be able to close this issue now.  Please lemme know if that is still not the case.
