### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [qitab/cl-protobufs#250]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id 4d9d28230315e05553d5575353a26271a278e9c9

*cl-protobufs* fails to build with the following error:

```
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE: Package COM.GOOGLE.BASE does not exist. Line: 12, Column: 48, File-Position: 343 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/.cache/common-lisp/sbcl-2.0.9.5-442f54894-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/cl-protobufs/aa82216c6f9a999fdc71ede466c4eb6f42917ef0/cl-protobufs-20201006-git/any.lisp" {10072473C3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A50103}>: COMPILE-FILE-ERROR while compiling #<PROTOBUF-SOURCE-FILE "cl-protobufs" "well-known-types" "any">

```

*cl-protobufs/tests* fails to build because of a failure in  _cl-protobufs_.

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/cl-protobufs.html)

**Comment by Slids** [comment]
How did you get this failure?
Could you tell me the reproduction steps?

**Comment by quicklisp** [comment]
My mistake - this is due to a different version of protoc-gen-lisp installed.

But this raises a new issue. https://github.com/brown/protobuf/ also wants protoc-gen-lisp for its version of the library. They both can't be installed with the same name.

ALso, getting `Unhandled CL-PROTOBUFS:PROTOBUF-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A30083}>: Could not find file "type.proto" imported by #<CL-PROTOBUFS:FILE-DESCRIPTOR API (package google.protobuf) {1007196CA3}>` when trying to build with the matching `protoc-gen-lisp` for the qitab cl-protobufs project.

**Comment by Slids** [comment]
Yea, we borrowed a lot from browns protoc code, we should probably change then name,
I'll do that shortly (tomorrow?)

------------------------------------------
As for the second comment:
Interesting, I've never seen that failure and all of the tests are passing CI.
The type.proto is here: It's here: https://github.com/qitab/cl-protobufs/blob/master/google/protobuf/type.proto . 

I can't see a reference in the file-descriptor code to type.proto so I'm even more clueless...

**Comment by sjl** [comment]
I see the same `Could not find file "type.proto"` error when trying to load `cl-protobufs` in a fresh REPL.  But if I choose restart 0 (`TRY-RECOMPILING`) it succeeds.

Full log: https://gist.github.com/49f025f777fa2c0da3e3bf97f18abdb7

**Comment by Slids** [comment]
Hoy a fix #266

**Comment by quicklisp** [comment]
> we should probably change then name, I'll do that shortly (tomorrow?)

Did this ever happen?

**Comment by Slids** [comment]
Did not, theres a hook I'm missing somewhere...

**Comment by Slids** [comment]
I think it deserves it's own issue though: https://github.com/qitab/cl-protobufs/issues/276
