### ISSUE TITLE
Find a way to cache protobuf install

### ISSUE THREAD

**Issue by Slids** [qitab/cl-protobufs#312]
It's crazy we rebuild it on every submit.
Shouldn't we be able to cache?

**Comment by groszewn** [comment]
https://github.com/actions/cache#skipping-steps-based-on-cache-hit should be helpful here.

**Comment by bkuehnert** [comment]
Fixed with 98c2c64. The ubuntu packages `libprotoc-dev` and `libprotobuf-dev` provide the headers needed for the lisp protoc plugin. So, we can just use that instead for CI (and we should probably be suggesting the same for our install guide)
