### ISSUE TITLE
consider add descriptor.proto?

### ISSUE THREAD

**Issue by jidibinlin** [qitab/cl-protobufs#370]

**Comment by Slids** [comment]
It would take quite a bit of work to do it properly.
Not a bad idea, but something I'd probably give a 
low priority, medium effort, low return rating.

Do you have a reason for wanting it?

**Comment by Slids** [comment]
Unless you mean literally just adding the proto file to this repo?

**Comment by jidibinlin** [comment]
I have a proto file need to import descriptor.proto。buf if cl-protobufs didn`t load descriptor.proto, I have no idea to load my proto file in my project。

what i need is add descripor.proto to cl-protobufs well-known-types module   like cl-protobufs/test did

**Comment by Slids** [comment]
You have other proto files in your project, so just add it to your project?
We have plenty examples of loading proto files in cl-protobufs.asd.

**Comment by jidibinlin** [comment]
But cl-protobufs already copied the descriptor.proto to google/protobufs/ directory。

**Comment by Slids** [comment]
So we were talking about too kinda different things, I was overthinking things.
So the ask is to add a module  "descriptor" with protobuf-source-file "descriptor"?

**Comment by jidibinlin** [comment]
@Slids Yes.

**Comment by Slids** [comment]
Done.
