### ISSUE TITLE
Loading in Lispworks 8.0.1 with quicklisp fails

### ISSUE THREAD

**Issue by dmsurti** [qitab/cl-protobufs#377]
- Lispworks Version: 8.0.1 (64-bit) for macOS
- mac OS version: Ventura 13.0
- mac Silicon: Intel 

When I attempt to load cl-protobufs using quicklisp, I get the following error:

```
CL-USER 5 > (ql:quickload :cl-protobufs)
To load "cl-protobufs":
  Load 1 ASDF system:
    cl-protobufs
; Loading "cl-protobufs"

**++++ Error between functions:
  Reader cannot find package LISPWORKS-FLOAT.

**++++ Error between functions:
  Reader cannot find package LISPWORKS-FLOAT.

**++++ Error between functions:
  Reader cannot find package LISPWORKS-FLOAT.

**++++ Error between functions:
  Reader cannot find package LISPWORKS-FLOAT.
; *** 4 errors detected, no fasl file produced.

Error: COMPILE-FILE-ERROR while compiling
#<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-protobufs" "models" "float-bits">
  1 (continue) Retry compiling
#<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-protobufs" "models" "float-bits">.
  2 Continue, treating compiling
#<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-protobufs" "models" "float-bits">
    as having been successful.
  3 Retry ASDF operation.
  4 Retry ASDF operation after resetting the configuration.
  5 Retry ASDF operation.
  6 Retry ASDF operation after resetting the configuration.
  7 (abort) Give up on "cl-protobufs"
  8 Register local projects and try again.
  9 Return to top loop level 0.
```

Any inputs to resolve this?

Just a note: Works fine on the same mac with SBCL 2.2.10

**Comment by Slids** [comment]
I try to keep this working for ABCL, SBCL, and CCL.
I would be very happy if someone got this to work with lispworks, 
but afaik nobodies worked on it yet.

**Comment by dmsurti** [comment]
@Slids Sure, I will try to resolve this issue. Can you give me some quick hints looking at the error trace? Thanks.

**Comment by Slids** [comment]
This is occuring in flat-bits.lisp: https://github.com/qitab/cl-protobufs/blob/bf5447065714a9f5b1b6ce6d0512fd99b4105e76/float-bits.lisp

will have to replace `lispworks-float:???` with the correct ??? in the correct package.

**Comment by Slids** [comment]
Working on https://github.com/qitab/cl-protobufs/pull/378
which should resolve this issue, if there are more afterwords happy to work with you!
