### ISSUE TITLE
missing header <google/protobuf/stubs/strutil.h>

### ISSUE THREAD

**Issue by minutello** [qitab/cl-protobufs#403]
It's not possible to build the CL plugin without this header file (among others), which is missing from the official repo, and can't be found anywhere, because it's a Google internal file (as it seems), and they don't want to expose it as public API:
```
<google/protobuf/stubs/strutil.h>
```
My question: is there any place on the interwebs to get the missing header files? I tried some workaround which compiles, but then it becomes a linking nightmare...

**Comment by bkuehnert** [comment]
Hi, thanks for the issue!  We're currently working on fixing the install instructions to work with the latest protobuf release (#402). In the meantime, you may have luck using an older release of protobuf: https://github.com/protocolbuffers/protobuf/tree/3.18.x. This version at least has `google/protobuf/stubs/strutil.h`.

**Comment by minutello** [comment]
Thanks for the quick reply, yes the older release has all files.
