### ISSUE TITLE
Use cl-protobufs 'passively' with already generated *.lisp files from *.proto?

### ISSUE THREAD

**Issue by minutello** [qitab/cl-protobufs#407]
This is more of a **feature request** than an issue, but it's certainly important:

What about using cl-protobufs on e.g. a mobile device, where we don't have (and don't need) the 'protoc' executable installed, because the respective *.lisp files have already been generated.

In other words: what about just a **passive** use of a minimal version of cl-protobufs, without full installation?

Is this currently possible? (Looking at the JS protobufs implementation, they certainly seem to provide this.)

**Comment by minutello** [comment]
Replying to myself: I hacked something together which works, I basically just included the generated `*.lisp` files from the included `*.proto` files, made some small adaption, and it works fine!

**Comment by Slids** [comment]
All protoc does is generate a file that lisp reads, so yip, thats the best way!
I'm closing this as I don't see what more you want.

**Comment by minutello** [comment]
ok thanks!
